---
role_name_check: 1
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:22.04
    privileged: true
    pre_build_image: true
